export const LESSONS_PAYMENT_AMOUNT = "10.00";
export const LESSONS_PAYMENT_CURRENCY = "CAD";
export const LESSONS_PAYMENT_LABEL = `${LESSONS_PAYMENT_AMOUNT} ${LESSONS_PAYMENT_CURRENCY}`;
export const LESSONS_PAYMENT_DISPLAY = `$${LESSONS_PAYMENT_AMOUNT}`;
